# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 06 Mar 2007 08:53:24 +0100
*               @user         8
*               @admin      255
*	@ALL	16
