<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 06 Mar 2007 08:53:24 +0100
 */
$conf['title'] = 'MayflowerWiki';
$conf['lang'] = 'en';
$conf['useacl'] = 1;
$conf['superuser'] = 'root';